### ISSUE TITLE
[一般]修改当前租户登录人的资源权限后，界面菜单刷新不更新，需要退出重新登录才显示正常

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-WEB#3]
[概要]：[一般]修改当前租户登录人的资源权限后，界面菜单刷新不更新，需要退出重新登录才显示正常
[详细步骤]：
1.【用户门户】注册租户A后， 【管理门户】审核通过后，并租户A登录用户门户                       
2.【管理门户】给租户A再分配其他资源权限
3.【用户门户】刷新租户A界面，菜单权限不更新，需要退出后重新登录，权限才正常显示
[实际结果]：
修改菜单权限后，界面不及时刷新，
[预期结果]:
界面及时权限，显示正常，不需要重新登录。

**Comment by oriiro** [comment]
这个预期要达到什么效果？实施刷新吗？ @xiexm

**Comment by oriiro** [comment]
@zhangft  涛姐这个需要探讨一下

**Comment by zhaolijing1990** [comment]
经确认，暂时不解决

**Comment by xiexm** [comment]
问题不修改，正常关闭
