### ISSUE TITLE
用户门户：界面没有显示当前登录用户

### ISSUE THREAD

**Issue by sunhongzhen** [AIPaaS/PaaS-FE-WEB#5]
用户门户：界面没有当前登录用户的信息提示。

**Comment by mapl-pisces** [comment]
1）、提测的功能说明：用户门户：界面显示当前登录用户的信息提示
2）、代码分支说明：https://github.com/AIPaaS/PAAS-FE-WEB.git  develop 
3）、配置信息说明：无
4）、数据库说明：无
5）、是否有特殊的第三方软件安装：无
